eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${vcap.services.pwa-eureka-service.credentials.uri}/eureka/
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    nonSecurePort: 80
