spring:
  application:
    name: system-events-microservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/SystemEventsDB
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  config:
    import=optional:configserver:http://localhost:8888/:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: localhost

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate=DEBUG:

server:
  port: 8090

grpc:
  server:
    port=9090: