spring:
  application:
    name: order-microservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/OrderDB
    username: root
    password: Infobip2021!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate=DEBUG:


grpc:
  server:
    host: localhost
    port: 9090